source CheckingTripleFrictionPendulum_1DDynamics_ConstFriction.tcl
source CheckingTripleFrictionPendulum_1DDynamics_VariableFriction.tcl
source CheckingTripleFrictionPendulum_2DDynamic_ConstFriction.tcl
source CheckingTripleFrictionPendulum_2DDynamic_VariableFriction.tcl
source CheckingTripleFrictionPendulum_3DDynamic_ConstFriction.tcl
source CheckingTripleFrictionPendulum_3DDynamic_VariableFriction.tcl
source CheckingTripleFrictionPendulum_StaticCyclicPushover.tcl
